### ISSUE TITLE
Forward Analysis Evaluation Issue

### ISSUE THREAD

**Issue by CharlieChenyuZhang** [amgrubb/Leaf2.0#14]
In the case below, when you click on evaluation, Goal_0 and Goal_8 are updated to Unknown. If we change Taskl_2 to Satisfied or Partially Satisfied then click on evaluation, the graph doesn't get updated. 

<img width="472" alt="screen shot 2018-10-21 at 12 10 07 pm" src="https://user-images.githubusercontent.com/22360911/47329928-71ca3e80-d644-11e8-93f3-7f918341aae7.png">

**Comment by CharlieChenyuZhang** [comment]
The current tool still has this issue. I am not sure if this is the correct behaviour or not.

**Comment by amgrubb** [comment]
This is not a bug, because Task_1 is none.
