### ISSUE TITLE
Dependency link doesn't work in Forward Analysis

### ISSUE THREAD

**Issue by CharlieChenyuZhang** [amgrubb/Leaf2.0#17]

**Comment by amgrubb** [comment]
Please add a description to the Issue including screen shots of incorrect behaviour.

**Comment by CharlieChenyuZhang** [comment]
![capture](https://user-images.githubusercontent.com/22360911/50367274-02da6a80-054d-11e9-8a42-754757f5a286.PNG)

When Task_2 is set to be satisfied, the forward analysis doesn't work.

**Comment by CharlieChenyuZhang** [comment]
As it turns out, dependency has the wrong direction of evaluation. In the current implementation, if Task_1 was satisfied, after the forward analysis, Task_2 is satisfied.

**Comment by CharlieChenyuZhang** [comment]
fixed and have requested the pull request
