### ISSUE TITLE
Weird behavior for D in dependency

### ISSUE THREAD

**Issue by jenhork** [amgrubb/Leaf2.0#2]
The D symbol in the dependency link looks ok, but when one moves or bends the dependency link it moves to strange places, see pic.  
![dweirdness](https://user-images.githubusercontent.com/7395460/28828644-a1548828-76d1-11e7-9560-0356ad5de7c5.jpg)

**Comment by amgrubb** [comment]
I created a temporary work around, until we decide what the link should look like.
I added the word depends and moved the D to the end of the link.

![screen shot 2017-11-01 at 7 06 19 pm](https://user-images.githubusercontent.com/6596937/32302187-c9a294f6-bf37-11e7-9a4b-c4fc7bfdb1d4.png)
