### ISSUE TITLE
Cannot un-click element.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/Leaf2.0#7]
We received a bunch of complaints about not being able to un-click an element. I was finally able to reproduce the bug (see screenshot).
Separate Recycling cannot be un-clicked.

![screen shot 2018-07-03 at 10 07 03 am](https://user-images.githubusercontent.com/6596937/42412859-9047a39a-81e2-11e8-95f1-dcd6458a6a7e.png)

**Comment by CharlieChenyuZhang** [comment]
The bug occurs because the code only detects when the node is in the cycle. It failed to detect the case when the path includes the cycle which doesn't include the node that we clicked on.

**Comment by amgrubb** [comment]
You should create a pull request for this issue if it is fixed and tested.

**Comment by CharlieChenyuZhang** [comment]
I created a pull request. Waiting for someone to review and merge.
