### ISSUE TITLE
Fix potential vulnerability.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/Leaf2.0#8]
![screen shot 2018-07-11 at 5 15 55 pm](https://user-images.githubusercontent.com/6596937/42599713-2392098a-852e-11e8-8758-414cca7823e4.png)

**Comment by CharlieChenyuZhang** [comment]
I don't have the access to review the vulnerable dependency message, as "only the owner of this repository can see" it. 

Could you click on it and let me know what line is affected? 

I think the simple fix is to take off the line 12 in the Leaf2.0/leaf-ui/plugins/chart/package.json file.

**Comment by amgrubb** [comment]
Fixed!
